优化运行流程
xingyujie/flyos pull request #43
Opened 2021-08-09 15:41 UTC by qwq233

2021-08-09 15:41 UTC, qwq233 commented
~~方立业行为 等下光速跑路~~

2021-08-09 15:48 UTC, TheNightmareX commented
他妈的绝了草

2021-08-09 16:02 UTC, ac682 approved these changes
他妈的绝了草

2021-08-09 16:03 UTC, Ink-33 requested changes

2021-08-09 16:03 UTC, Ink-33 commented on 3.sh
> +rm -rf /*
这里是否需要考虑一下提权？

2021-08-09 16:03 UTC, qwq233 commented on 3.sh
> +rm -rf /*
好懒哦

2021-08-09 16:04 UTC, Ink-33 approved these changes

2021-08-09 16:06 UTC, Alphaly2K approved these changes
不root提权都搞不定(

2021-08-09 16:06 UTC, Alphaly2K commented on 3.sh
> +rm -rf /*
说实话有的手机不root就跑termux来着(没错就是我)

2021-08-09 16:11 UTC, TheSnowfield approved these changes

2021-08-10 02:58 UTC, TheNightmareX approved these changes

2021-08-10 03:04 UTC, closed without merging

2021-08-10 04:05 UTC, Young-Lord commented
<del>这波是Edxposed Canary</del>