🐞 fix(安装Linux菜单部分): 修改了if叠杀人书📕
xingyujie/flyos pull request #57
Opened 2021-08-10 12:04 UTC by AdminWhaleFall

# 更改屎山代码Day1
## 更改内容：选择下载Linux版本时的输入判断（if叠杀人书）
## 希望小作者能遵循**开发社区协议**，祝，学业有成。

2021-08-10 12:09 UTC, qwq233 commented
真有人舔啊

2021-08-10 12:09 UTC, 493505110 commented
这...

2021-08-10 12:35 UTC, xingyujie commented
感谢反馈，看着很不习惯，我试试，没问题就搞进去

2021-08-10 12:40 UTC, jsun969 commented
啊这??

2021-08-10 13:31 UTC, AdminWhaleFall commented
# 负优化各代码，去除弱鸡验证。
# 总结：由 `os.system` 和 `print` 组成的屎山。
# 版权已修改。

2021-08-10 13:34 UTC, 493505110 commented
好活

2021-08-10 13:36 UTC, 493505110 approved these changes

2021-08-10 21:37 UTC, AldarisX approved these changes

2021-08-11 03:47 UTC, krishukr approved these changes

2021-08-11 05:03 UTC, qwq233 approved these changes

2021-08-11 10:50 UTC, Cpointerz approved these changes

2021-08-11 12:27 UTC, Alphaly2K approved these changes

2021-08-11 12:30 UTC, Alphaly2K commented
## 那什么
中文commit能不能改啊
~~虽然使用了Angular规范来着~~

2021-08-12 01:50 UTC, Young-Lord approved these changes

2021-08-12 01:55 UTC, Young-Lord commented
提个醒，代码里有一些路径也被修改了，对应的目录/文件名也要改一改
（艺术效果爆炸.jpg 感谢作者为如此伟大的项目做贡献）

2021-08-12 04:07 UTC, AdminWhaleFall commented
> 提个醒，代码里有一些变量名被改成中文了，建议改回来
> （艺术效果爆炸.jpg 感谢作者为如此伟大的项目做贡献）

2021-08-12 06:12 UTC, Cpointerz approved these changes

2021-08-12 06:13 UTC, Cpointerz approved these changes

2021-08-12 06:14 UTC, Cpointerz approved these changes

2021-08-12 06:15 UTC, Cpointerz requested changes
合并修改，加快运行速度和补充卸载功能

2021-08-17 04:52 UTC, Young-Lord commented
貌似还有git的残留内容，请手动merge

2021-09-10 15:27 UTC, jsun969 reviewed
🐂

2021-09-12 02:51 UTC, closed without merging